WomsBlog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("news.urls", namespace="news")),
]

news/urls.py
from django.urls import path

from news import views


app_name = "news"

urlpatterns = [
    path("", views.news_list, name="news_list"),
    path("single/<int:pk>/", views.new_single, name="new_single"),
]

news/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Category(models.Model):
    """Категория"""

    title = models.CharField(verbose_name="Название", max_length=50)
    
    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        
    def __str__(self):
        return self.title
    
    
class Tag(models.Model):
    """Тег"""
    
    title = models.CharField(verbose_name="Тег", max_length=50)
    
    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"
        
    def __str__(self):
        return self.title
    
    
class News(models.Model):
    """Новость"""
    
    user = models.ForeignKey(User, verbose_name="Автор", on_delete=models.CASCADE)
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True)
    title = models.CharField(verbose_name="Заголовок", max_length=100)
    text_min = models.TextField(verbose_name="Мин. текст", max_length=350)
    text = models.TextField(verbose_name="Текст статьи")
    tags = models.ManyToManyField(Tag, verbose_name="Теги")
    created = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)
    description = models.CharField(verbose_name="Описание", max_length=100)
    keywords = models.CharField(verbose_name="Ключевые слова", max_length=50)
    
    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
        
    def __str__(self):
        return self.title

news/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from news.models import News


def news_list(request):
    """Список статей"""
    news = News.objects.all()
    context = {"news": news}
    return render(request, "news/news_list.html", context)


def new_single(request, pk):
    """Статья"""
    new = get_object_or_404(News, id=pk)
    context = {"new": new}
    return render(request, "news/new_single.html", context)

news/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block desc %}{% endblock desc %}">
    <meta name="keywords" content="{% block keywords %}{% endblock keywords %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

news/templates/news/base.html
{% extends "base.html" %}
{% block desc %}{% endblock desc %}
{% block keywords %}{% endblock keywords %}
{% block title %}{% endblock title %}
    {% block content %}

    {% endblock %}

news/templates/news/new_single.html
{% extends "news/base.html" %}
{% block desc %}{{ new.description }}{% endblock desc %}
{% block keywords %}{{ new.keywords }}{% endblock keywords %}
{% block title %}{{ new.title }}{% endblock title %}

{% block content %}
    <h1>{{ new.title }}</h1>
    <p>{{ new.text }}</p><hr>

    Категория - {{ new.category }}<br>
    Теги - {% for tag in new.tags.all %}
                {{ tag.title }}
            {% endfor %}<br>
    Автор: {{ new.user }} - {{ new.created }}
{% endblock %}

news/templates/news/news_list.html
{% for new in news %}
    <h2><a href="{% url 'news:new_single' pk=new.id %}">{{ new.title }}</a></h2>
    <p>{{ new.text_min }}</p>
    <p>{{ new.created }}</p>
{% endfor %}